print('CETAM-CENTRO DE EDUCAÇÃO TECNOLÓGIGA DO AMAZONAS')
print('CURSO:DESENVOLVIMENTO DE SISTEMA')
print('COMPONENTE: LINGUAGEM DE PROGRAMAÇÃO')
print('DATA:13/08/2025')
print('PROFESSOR:MICHALES CAMURÇA')
print('ALUNO: JOSÉ LUIZ SOUZA')
print('ATIVIDADE:  Porção Inteira Leia um número real e mostre apenas sua parte inteira')
numero_real = float(input("Digite um número real: "))
parte_inteira = int(numero_real)
print("A parte inteira é:", parte_inteira)
