print('CETAM-CENTRO DE EDUCAÇÃO TECNOLÓGIGA DO AMAZONAS')
print('CURSO:DESENVOLVIMENTO DE SISTEMA')
print('COMPONENTE: LINGUAGEM DE PROGRAMAÇÃO')
print('DATA:11/08/2025')
print('PROFESSOR:MICHALES CAMURÇA')
print('ALUNO: JOSÉ LUIZ SOUZA')
print('ATIVIDADE: Mostrar a tabuada (1 a 10) de um número')


numero = int(input('digite o número: '))
print(f'{numero} x 1 = {(numero * 1)}')
print(f'{numero} x 2 = {(numero * 2)}')
print(f'{numero} x 3 = {(numero * 3)}')
print(f'{numero} x 4 = {(numero * 4)}')
print(f'{numero} x 5 = {(numero * 5)}')
print(f'{numero} x 6 = {(numero * 6)}')
print(f'{numero} x 7 = {(numero * 7)}')
print(f'{numero} x 8 = {(numero * 8)}')
print(f'{numero} x 9 = {(numero * 9)}')
print(f'{numero} x 10 = {(numero * 10)}')
